---
- name: Ansible Sandbox
  hosts: all
  become: true
  roles:
    - cron
    - install_pkg
    - zsh
    - vim
    - docker
    - sshd


  pre_tasks:
    - name: 0️⃣  Load configuration (with defaults from example file)
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - default.config.yaml
        - config.yaml

  handlers:
    - name: Include handlers
      ansible.builtin.import_tasks: tasks/handlers.yaml

  tasks:
    - name: 1️⃣  Update all system packages
      ansible.builtin.include_tasks: tasks/update_system.yaml

    - name: 2️⃣  Change default hostname
      ansible.builtin.include_tasks: tasks/hostname.yaml
      when: change_default_hostname_enable
