---
# tasks file for ansible-raspberrypi-docker

# http://docs.ansible.com/ansible/latest/apt_module.html
- name: "Installe les paquets nécessaires à l'utilisation d'un dépôt HTTPS"
  become: true
  ansible.builtin.apt:
    pkg: "{{ item }}"
  loop: "{{ docker_apt_pkg }}"

# http://docs.ansible.com/ansible/latest/apt_key_module.html
- name: "Ajoute la clef officielle du dépôt Docker"
  become: true
  ansible.builtin.apt_key:
    url: "{{ docker_apt_key }}"
    state: present

# http://docs.ansible.com/ansible/latest/apt_repository_module.html
- name: "Ajoute le dépôt Docker"
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present
  register: install_docker_repository

- name: Check if docker-ce package is avalable
  ansible.builtin.command: apt-cache search docker-ce
  register: docker_ce_available
  changed_when: docker_ce_available.rc != 0
  failed_when: docker_ce_available.stdout == '' and docker_ce_available.skipped == True

- name: Installe le paquet docker-ce
  become: true
  ansible.builtin.apt:
    pkg: "docker-ce"
  when: not docker_ce_available.failed

- name: "Installe python-pip"
  become: true
  ansible.builtin.apt:
    pkg: "python3-pip"
  when: not docker_ce_available.failed

# http://docs.ansible.com/ansible/latest/pip_module.html
- name: "Installe docker-compose via pip"
  become: true
  ansible.builtin.pip:
    name: docker-compose
  when: not docker_ce_available.failed

# http://docs.ansible.com/ansible/latest/systemd_module.html
- name: "Configure Docker pour qu'il démarre au boot"
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  when: not docker_ce_available.failed

- name: "Ajoute l'utilisateur pi dans le groupe docker"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: true
  when: not docker_ce_available.failed

- name: "Supprime la swap"
  become: true
  ansible.builtin.systemd:
    name: dphys-swapfile
    state: stopped
    enabled: false
  when: not docker_ce_available.failed

- name: Reboot the Debian or Ubuntu server
  become: true
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible due to docker installation"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: not docker_ce_available.failed
