---
# Docker repository is added in the install package task.
- name: Check if docker-ce package is avalable
  ansible.builtin.command: apt-cache search docker-ce
  register: docker_ce_available
  changed_when: docker_ce_available.rc != 0
  failed_when: docker_ce_available.stdout == '' and docker_ce_available.skipped == True

- name: Installe le paquet docker-ce
  become: true
  ansible.builtin.apt:
    pkg: "docker-ce"
    update_cache: true
  when: not docker_ce_available.failed

- name: "Installe python-pip"
  become: true
  ansible.builtin.apt:
    pkg: "python3-pip"
  when: not docker_ce_available.failed

# http://docs.ansible.com/ansible/latest/pip_module.html
- name: "Installe docker-compose via pip"
  become: true
  ansible.builtin.pip:
    name: docker-compose
  when: not docker_ce_available.failed

# http://docs.ansible.com/ansible/latest/systemd_module.html
- name: "Configure Docker pour qu'il démarre au boot"
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  when: not docker_ce_available.failed

- name: "Ajoute l'utilisateur pi dans le groupe docker"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: true
  when: not docker_ce_available.failed

- name: "Supprime la swap"
  become: true
  ansible.builtin.systemd:
    name: dphys-swapfile
    state: stopped
    enabled: false
  when: not docker_ce_available.failed
  notify: Reboot the machine
