---
- name: Ensure .vim/{autoload,bundle} directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: false
    mode: 0750
  loop: "{{ vim_directory }}"

- name: Copy vim dotfile
  ansible.builtin.copy:
    src: "dotfiles/.vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750

- name: Verify that autoload folder exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
  register: vim_autoload_details

- name: Ensure vim-plug is in place
  ansible.builtin.get_url:
    url: "{{ vim_plug_url }}"
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    mode: 0644
  when: vim_autoload_details.stat.exists

- name: Perform the plugins installation with PlugInstall
  ansible.builtin.command: "vim -e -i NONE -c 'PlugInstall' -c 'PlugClean' -c 'qa'"
  ignore_errors: true
  register: ignore_errors_register
  when: vim_autoload_details.stat.exists
