---
vim_directory:
  - "{{ ansible_env.HOME }}/.vim"
  - "{{ ansible_env.HOME }}/.vim/autoload"
  - "{{ ansible_env.HOME }}/.vim/bundle"
  - "{{ ansible_env.HOME }}/.vim/plugged"
  - "{{ ansible_env.HOME }}/.vim/init"
vim_plug_url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim