---
- name: Ensure .vim/{autoload,bundle} directory exists
  become: false
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0750
  loop: "{{ vim_directory }}"

- name: Copy vim settings (1/2)
  become: false
  copy:
    src: "vim/.vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750

- name: Copy vim settings (2/2)
  become: false
  copy:
    src: "vim/init"
    dest: "{{ ansible_env.HOME }}/.vim"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750

- name: Verify that autoload folder exists
  become: false
  stat:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
  register: vim_autoload_details

- name: Ensure vim-plug is in place
  become: false
  get_url:
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    url: "{{ vim_plug_url }}"
  when: vim_autoload_details.stat.exists

- name: Perform the plugins installation with PlugInstall
  become: false
  shell: "vim -e -i NONE -c 'PlugInstall' -c 'PlugClean' -c 'qa'"
  ignore_errors: true
  when: vim_autoload_details.stat.exists